const BACKEND_ROUTES = {
  SETTING: '/admin/settings/',
  USER_LIST: '/admin/users/partners/',
  SINGLE_USER: 'admin/users/partners/:id/',
  USER_APPROVED: '/admin/users/partner/:id/verify-profile/',
  GET_PROFILE: '/admin/users/my-profile/',
  ADD_PROPERTY: '/admin/properties/',
  UPLOAD_IMAGE: 'file-object/upload-url',
  PROPERTY: '/admin/properties/:id/',
  AMENITIES: '/admin/properties/amenities/',
  TAGS: '/admin/tags/',
  HOME_LOAN: '/admin/properties/homeloan-partners/',
  DEVELOPER: '/admin/properties/developers/',
  COUNTRY: '/admin/location/countries/',
  STATE: '/admin/location/states/',
  CITY: '/admin/location/cities/',
  DISTRICT: '/admin/location/districts/',
  GET_TEAM_MEMBER: '/admin/users/partner/:id/team-members/',
  GET_USER_PROJECT: '/admin/users/partner/:id/projects/',
  GET_LOCALITIES: '/admin/location/localities/',
  COLLECTIONS: '/admin/properties/collections/',
  COLLECTION: '/admin/properties/collections/:id/',
  COLLECTION_PROPERTIES: '/admin/properties/',
  ADD_COLLECTION_PROPERTIES: '/admin/properties/',
  LEADS_DETAILS:'/admin/leads/:id/',
  LEADS:'/admin/leads/',
  PARTNER_LEAD:'/admin/leads/partner/:id/',
  DELETE_CONFIGURATION:'/admin/properties/configurations/:id/',
  BULK_UPLOAD:'/admin/properties/bulk-import/',
  BUYING_GUIDE:'/admin/buying-guides/',
  SINGLE_BUYING_GUIDE:'/admin/buying-guides/:id/',
  GET_TRANSACTION:'/admin/users/transactions/',
  VERIFY_OTP_COMMON:'/verify-otp/',
  GET_PAYMENTS:'/admin/users/payments/',
  GET_CUSTOMER:'/admin/users/customers/',
  PATCH_CUSTOMER:'/admin/users/customer/:id/',
  REFUND_REQUEST:'/admin/refunds/',
  RATING:'/admin/properties/:id/ratings/',
  NOTIFICATION:'/admin/notifications/',
  DEVICES: '/devices/',
}
export default BACKEND_ROUTES
